function COMPAR_SMTH(yrinch,julinch)
%
%  INPUT:
%  -----
%         yrinch:  YEAR PROCESSED                           CHARACTER
%         julinch:  STARTING JULIAN DAY TO PROCESS          CHARACTER
%
%  COMPAR_SMTH
%    This matlab routine takes the raw output data file generated by
%      METEDIT and compares the smoothed (Interval dependent)
%      to the unsmoothed data set for each of the land based stations
%    There are 2 subplots per page
%      Wind Speed
%      Wind Direction
%    May want to add the air and water temperature plot to determine
%      the stability of the air/sea interface.
%
% yrinch = '1989';
% julinch= '258';
filein1=['STNLOC-',yrinch,'-',julinch,'.dat'];
filein2=['metobs-',yrinch,'-',julinch,'-2NN.dat'];
filein3=['metobs-',yrinch,'-',julinch,'-TSMTH2NN.dat'];
%
%  Input Station Location File FORMAT
%  (I1.1,A8,I4.4,I3.3,A20,2I4.4,I1.1,I4,I3,1X,A8)
%  COLUMN 1
%       flag (1)
%       STATION ID
%  COLUMN 2
%       YEAR (1-4)
%       JULIAN DAY (5-7)
%       STATION NAME (8-27)
%  COLUMN 3
%       LATITUDE  (1-5)
%       LONGITUDE (6-9)
%  COLUMN 4
%       STATION ELEVATION ((1-3)
%  COLUMN 5
%       ANEMOMETER ELEVATION (1-2)
ii=0;
fid=fopen(filein1);
while 1
    ii=ii+1;
    tline = fgetl(fid);
    if ~ischar(tline), break, end
    stnnum(ii,:) = sscanf(tline(:,2:7),'%c');
    yrjul(ii,:) = sscanf(tline(:,10:16),'%c');
    stnid(ii,:)=  sscanf(tline(:,17:36),'%c');
    lat(ii,:) = sscanf(tline(:,37:40),'%c');
    long(ii,:) = sscanf(tline(:,41:44),'%c');
end
fclose(fid);
clear ii;
%  Covert from character to numerical values
%
xlat=str2num(lat)/100.;
xlong=-str2num(long)/100.;
yearin=str2num(yrjul(:,1:4));
juldate=str2num(yrjul(:,5:7));
usafid=stnnum(:,:);
%
%  -----------------------------------------------------------------------
%  Open the Input file containing land based met station data
%    1.  Column 1:                          (1:18)
%       a.  Date: (YYYY,JJJ,HH,MM)          (1:4, 5:7, 8:9, 10:11)
%       b.  FLAG FOR STATION (Airways == 6) (12:12)
%       c.  USAF ID NUMBER                  (13:18)
%   2-Blanks
%   2.  Column 2:
%       a.  Lake Flag  (Lake Michigan == 1) (21:21)
%       b.  Format Flag (LMD == 9)          (22:22)
%   3.  Column 3:  Air Temperature      (Deg C)
%   4.  Column 4:  Dew Point            (Deg C)
%   5.  Column 5:  Wind Direction       (Meteorlogical 0-deg from the north)
%   6.  Column 7:  Wind Speed           (m/s)
%   7.  Column 8:  Wind Gust            (m/s)
%   8.  Column 9:  Cloud Cover          (percent)
%   9.  Column 10:  Solar Radiation     (watts/m^2)
%  10.  Column 11:  Barometric Pressure (mb)
%  11.  Column 12:  Water Temp          (Deg C)
%  12.  Column 13:  Significant Height  (m)
%  13.  Column 14:  Wave Period         (s)
%  -----------------------------------------------------------------------
%
%  FIRST IS THE ORIGINAL UNSMOOTHED DATA to be used in NN from metedit
%filein=['METOBS_',yrinch,'_',julinch,'.dat'];
fid=fopen(filein2,'rt');
fmt0='%11c%*c%7c %f %f %f %f %f %f %f %f %f %f';
dat0=textscan(fid,fmt0);
fclose(fid);
%Parse data
dum=dat0{1};
yr_met=str2num(dum(:,1:4));
jul_met=str2num(dum(:,5:7));
hr_met =str2num(dum(:,8:9));
mn_met =str2num(dum(:,10:11));
usaf_met=dat0{2};
u_met = dat0{6};
v_met = dat0{7};
dir_met = 180*atan2(v_met,u_met) / pi;
dir_met = 270 - dir_met;
ifx=find(dir_met < 0);
dir_met(ifx)=dir_met(ifx) + 360;
clear ifx;
ifx2=find(dir_met >= 360);
dir_met(ifx2) = dir_met(ifx2) - 360;
clear ifx2;
spd_met = dat0{8};
ifx2=find(spd_met == 999.9);
spd_met(ifx2) = NaN;
dir_met(ifx2) = NaN;
clear ifx2;
%                     NOTE NO Barometric Pressure in metedit as yet.
% barp_met = dat0{11};
% ifx=find(barp_met == 9999.9);
% barp_met(ifx) = NaN;
clear dum dat0;
%
%  Load in the smoothed data (to be used in NN output from metedit)
%filein=['METOBS_',yrinch,'_',julinch,'_TSMTH.dat'];
%
fid=fopen(filein3,'rt');
fmt0='%11c%*c%7c %f %f %f %f %f %f %f %f %f %f';
dat0=textscan(fid,fmt0);
fclose(fid);
%Parse data
dum=dat0{1};
yr2prc=str2num(dum(:,1:4));
jul2prc=str2num(dum(:,5:7));
hr2prc =str2num(dum(:,8:9));
mn2prc =str2num(dum(:,10:11));
usaf2prc=dat0{2};
%  Fill flagged (missing data with NaN's)
%  Fill flagged (missing data with NaN's)
u_prc = dat0{6};
v_prc = dat0{7};
wnddprc = 180*atan2(v_prc,u_prc) / pi;
wnddprc = 270 - wnddprc;
ifx=find(wnddprc < 0);
wnddprc(ifx)=wnddprc(ifx) + 360;
clear ifx;
ifx2=find(wnddprc >= 360);
wnddprc(ifx2) = wnddprc(ifx2) - 360;
clear ifx2;
spdprc = dat0{8};
ifx=find(spdprc == 999.9);
spdprc(ifx)= NaN;
wnddprc(ifx) = NaN;
% barpprc = dat0{11};
% ifx=find(barpprc == 9999.9);
% barpprc(ifx) = NaN;
clear dum dat0;
%
%  Determine which stations in Location file are used
%  Look at only the first set of information
%       the First JULIAN DAY / HR=0 / MIN=0
%
julstrt = str2num(julinch);
active  = find(jul2prc == julstrt & hr2prc == 0 & mn2prc == 0);
%
%   Multiple panels
%       Wind Speed
%       Wind Direction
%       Barometric Pressure
%       (need to add barometric pressure to output file)
%
%  Now pull appropriate station and then plot up the wind speed, direction
%      times are equilivant for both sets.
%      Have place holder for the barometric pressure
%
for k1=1:length(active)
    pltfile=[yrinch,'_',julinch,'_',stnnum(k1,:)];
    titch1=['Comparison Station Inputs RAW and Time SMOOTHED'];
    titch2=['Station Number:  ',stnnum(k1,:)];
    titch3=['Station:  ',stnid(k1,:)];
    titch4=['Location:  Long / Lat :  ',num2str(xlong(k1)),'\circ  /  ',...
        num2str(xlat(k1)),'\circ'];
    titlT = [{titch1};{titch2};{titch3};{titch4}];
    xlabT = ['Month/Day in  ',yrinch];
    k21=strmatch(usafid(k1,:),usaf2prc(:,1:6),'exact');
    k22=strmatch(usafid(k1,:),usaf_met(:,1:6),'exact');
    if ~isempty(k21) && ~isempty(k22);
        mtime0=datenum(yr_met(k22),1,0) + jul_met(k22) + hr_met(k22)/24;
        mtimeS=datenum(yr2prc(k21),1,0) + jul2prc(k21) + hr2prc(k21)/24;
        minxx=floor(min(min(mtime0),min(mtimeS)));
        maxxx=ceil(max(max(mtime0),max(mtimeS)));
        xlimxx=[minxx, maxxx];
        subplot(2,1,1)
        H=plot(mtime0,spd_met(k22),'.k:',mtimeS,spdprc(k21),'.r-');
        ymax=ceil(max(max(spdprc(k21)),max(spd_met(k22))));
        mm=find(isnan(spdprc(k21)));
        datchk=length(mm)-length(spdprc(k21));
        if datchk == 0;
            xticks=get(gca,'XTick');
            xx=datestr(xticks,6);
            set(gca,'XTick',xticks,'XTicklabel',xx);
            ylimyy=[0,10];
            set(gca,'Ylim',ylimyy);
            set(gca,'Xlim',xlimxx);
            text(xticks(2),5,'NO WIND SPEED DATA','Color',[1,0,0]);
        else
            xticks=get(gca,'XTick');
            xx=datestr(xticks,6);
            set(gca,'XTick',xticks,'XTicklabel',xx);
            ylimyy=get(gca,'Ylim');
            ylimmy=[0,ymax];
            set(gca,'Ylim',ylimyy);
            set(gca,'Xlim',xlimxx);
        end
        grid
        ylabel('Wind Spd [m/s]');
        title(titlT)
        hleg=legend(H,'RAW-DATA','SMOOTHED');
        po=get(hleg,'position');
        po=[0.825 0.925 0.08 0.03];
        set(hleg,'position',po);
        clear H; clear mm; clear datchk;
        
        %  Wind Direction (Meteorological)
        subplot(2,1,2)
        H=plot(mtime0,dir_met(k22),'.k:',mtimeS,wnddprc(k21),'.r-');
        xticks=get(gca,'XTick');
        xx=datestr(xticks,6);
        set(gca,'XTick',xticks,'XTicklabel',xx);
        ylimy=get(gca,'Ylim');
        ylimmx=[0,360];
        mm=find(isnan(wnddprc(k21)));
        datchk=length(mm)-length(wnddprc(k21));
        if datchk == 0;
            text(xticks(2),180,'NO WIND DIRECTION DATA','Color',[1,0,0]);
        end
        set(gca,'Ylim',ylimmx);
        set(gca,'Xlim',xlimxx);
        grid
        ylabel('Wind Dir [\circ-MET]');
        xlabel(xlabT);
        %  Barometric Pressure (add in the Metedit results when ready)
%         subplot(3,1,3)
%         plot(mtime0,barp_met(k22),'.k:',mtimeS,barpprc(k21),'.r-')
%         xticks=get(gca,'XTick');
%         xx=datestr(xticks,6);
%         mm=find(isnan(barpprc(k21)));
%         datchk=length(mm)-length(barpprc(k21));
%         if datchk == 0;
%             ylimm=[900,1060];
%             set(gca,'Ylim',ylimm)
%             text(xticks(2),980,'NO SEA LEVEL PRESSURE DATA','Color',[1,0,0]);
%         end
%         set(gca,'XTick',xticks,'XTicklabel',xx);
%         set(gca,'Xlim',xlimxx);
%         grid
%         ylabel('Sea Level Press [mb]');
%         xlabel(xlabT);
        eval(['print -dpng -r600 CStimplt_',pltfile]);
        clf
    end
    clf
end